### ISSUE TITLE
Make all measures return a vector given vector arguments, even AUC, and so forth

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBase.jl#308]
Picking up one item from #299 in particular, to get some feedback:

Currently, depending on the value of the trait `reports_each_observation` a measure applied to pair of vectors (predictions, observations) either returns a *scalar* (eg, `AUC()`) or a vector of the same length (eg, `L2()`). In the case of `evaluate!` this means measures of the first kind report `missing` instead of having a proper `per_observation` component to the result. 

I propose the following breaking change to avoid a lot of unnecessary case distinctions (eg, in Bayesian optimisation methods making use of per-observation estimates of performance) and may be less confusing too: **All measures return a vector**. If `reports_each_observation=false`, we simply make the vector a constant vector.

**Comment by azev77** [comment]
So `rmse(ŷ, y)` will return a 1-dimensional vector instead of a real number?

**Comment by ablaom** [comment]
Yeah, except its called `rms`.

**Comment by CameronBieganek** [comment]
Hold on a second. @azev77 I think @ablaom means the following:

```julia
julia> rms([1, 2, 3], [4, 3, 5])
3-element Array{Float64,1}:
 2.160246899469287
 2.160246899469287
 2.160246899469287
```

That seems a bit goofy to me. I think anyone who calls `rms` or `auc` outside of `evaluate!` will be pretty surprised...

**Comment by ablaom** [comment]
Yes, to be clear, that is exactly what I meant. @CameronBieganek  thanks for the feedback!

**Comment by ablaom** [comment]
There does not appear to be the stomach for this, so closing.
