### ISSUE TITLE
Add BrierScore for `Continuous` targets and assorted Distributions

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBase.jl#395]
Requires https://github.com/JuliaStats/Distributions.jl/issues/806 

At time of writing MLJBase has **no** probabilistic measures for `Continuous` data.

cc @DilumAluthge

**Comment by DilumAluthge** [comment]
In my particular use case, I have implemented `MLJModelInterface.predict_mean`. It returns a `Vector{Float64}`.

Is there a way to e.g. tell `evaluate!` to use `MLJModelInterface.predict_mean` instead of `MLJModelInterface.predict`?

**Comment by DilumAluthge** [comment]
I just saw your Slack reply - so I can accomplish this with `operation=predict_mean`?

**Comment by ablaom** [comment]
Yes, you give `evaluate!` the keyword argument `operation=predict_mean`.
