### ISSUE TITLE
`evaluate` and `evaluate!` should return a `struct` instead of a `NamedTuple`

### ISSUE THREAD

**Issue by OkonSamuel** [JuliaAI/MLJBase.jl#408]
with the recent increase in the size of `NamedTuple` returned by `evaluate` and `evaluate!`, I would suggest that these methods return a custom immutable `struct` rather than a `NamedTuple`. The reason for this is so we can customize the display of the struct and define some cool methods for extracting the parameters of the struct. This change should not affect other methods which are dependent on `evaluate` and `evaluate!`.
```julia
julia> struct A
            x::Int
          end
 
julia> st = A(1)
A(1)

julia> nt = (x=1,)
(x = 1,)

julia> st.x
1

julia> nt.x
1

end
```
thoughts Anyone?

**Comment by CameronBieganek** [comment]
Makes sense to me. Another advantage of having a struct output is that it can have its own docstring.

In general I think there are a few places in MLJ where it might be nice to have structs instead of named tuples, so that the expected data types in various places can be better documented.

**Comment by ablaom** [comment]
Resolved.
