### ISSUE TITLE
1.0 checklist

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBase.jl#638]
Mostly, issues will be given a "version 1.0" label as this issue has.

This is for miscellany:

- [x] Remove depwarnings for original @pipeline  and @from_network syntax, and the code/tests for these

**Comment by DilumAluthge** [comment]
My favorite issue title 😄

**Comment by ablaom** [comment]
Well, this is going to take a while. But I do think 21 consecutive patch releases is sign that we should probably start this.
