### ISSUE TITLE
Improvements for unsupervised models that make probabilistic predictions

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBase.jl#656]
The GMMClusterer is such a model (and it has *only* a `predict` and no `transform`). I believe it is the *only* such model at present. 

We should implement all of the following methods for extracting *deterministic* predictions for such models. At time of writing these don't work:

- [x] Call `predict_mode` (it seems this is not overloaded in ~~MLJModelInterface~~ MLJBase for unsupervised models, only unsupervised ones).  Assigning self, @ablaom 
- [ ] Put in a pipeline with `v -> mode.(v)` . Doesn't work because of https://github.com/JuliaAI/MLJClusteringInterface.jl/issues/10 but this will be resolved by https://github.com/JuliaAI/MLJBase.jl/pull/639

**Comment by davnn** [comment]
I'm thinking about extending the type hierarchy as follows

```julia
abstract type Supervised   <: Model end
abstract type Unsupervised <: Model end
abstract type Static       <: Model end

# todo: create the following with a macro for all base types...
abstract type SupervisedTransformer   <: Supervised end
abstract type SupervisedProbabilistic <: Supervised end
abstract type SupervisedDeterministic <: Supervised end
abstract type SupervisedInterval      <: Supervised end

abstract type UnsupervisedTransformer   <: Unsupervised end
abstract type UnsupervisedProbabilistic <: Unsupervised end
abstract type UnsupervisedDeterministic <: Unsupervised end
abstract type UnsupervisedInterval      <: Unsupervised end

abstract type StaticTransformer   <: Static end
abstract type StaticProbabilistic <: Static end
abstract type StaticDeterministic <: Static end
abstract type StaticInterval      <: Static end
```

Subtyping `Supervised`, `Unsupervised` or `Static` should probably not be possible then as we are missing the *default output* of the model, or if it is possible there would just be no default output. Wouldn't such a hierarchy be more flexible for future use cases?

**Comment by ablaom** [comment]
closing as essentially tracked by the pipeline PR
