### ISSUE TITLE
@mlj_model macro fails on  negative default  args [needs docs for way around]

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/MLJBase.jl#68]
```julia
julia> @mlj_model mutable struct Blah
       a::Int = -1::(_ > -2)
       end
ERROR: syntax: extra token "::" after end of expression
```

I'm investigating, the issue is that `-5` is effectively  an op

**Comment by tlienart** [comment]
right so that won't be easy to directly fix; there's something to do with when that  `-` is evaluated. Interestingly  this works fine:

```
neg(a) = -a
@mlj_model mutable struct Foo
  a::Int = neg(1)::(_ > -2)
end
```

So I guess we can either try the hard way which is to fix this (it's  not clear to me  how); or document that users should use `neg` for negative default vals and maybe export that `neg` though that may be a bit hacky.

**Comment by tlienart** [comment]
A bit less hacky:

```julia
@mlj_model mutable struct Bar
    a::Int = (-)(1)::(_ > -2)
end
```

**Comment by ablaom** [comment]
@tlienart Thanks for that. Good catch.

While this is annoying, I think it low priority. I vote for the documented hack.

**Comment by ablaom** [comment]
Closing in favour of above MLJ 504

**Comment by ablaom** [comment]
MLJ 504 is just a documentation issue.

**Comment by ablaom** [comment]
Since this issue was opened we've not actually bumped against it.  I think the documentation warning, already added suffices and am closing.
