### ISSUE TITLE
target_scitype for SupervisedPipelines

### ISSUE THREAD

**Issue by olivierlabayle** [JuliaAI/MLJBase.jl#710]
Hello everyone,

I think we could add a `target_scitype` directive for SupervisedPipelines.

```julia

LinearRegressor = @load LinearRegressor pkg=MLJLinearModels verbosity = 0
pipe = (X -> coerce(X, :age=>Continuous)) |> ContinuousEncoder() |> LinearRegressor()
target_scitype(pipe)
```

will result in Unknown.

The following should work and happy to try and make the change if your concern is somewhere else:

```julia

target_scitype(p::SupervisedPipeline) = target_scitype(supervised_component(p))
```

**Comment by ablaom** [comment]
Thanks for opening this issue @olivierlabayle and already looking into a fix. 

There is the possibility that the supervised component is not at the end of the pipeline, in which case we should return `Unknown` to be safe as we have no way of knowing how an arbitrary callable will transform the scientific type.
