### ISSUE TITLE
documentation of log_loss/LogLoss

### ISSUE THREAD

**Issue by jbrea** [JuliaAI/MLJBase.jl#716]
It would be nice to have better documentation for `log_loss` (No documentation found.) and `LogLoss` (references unexported `LogScore`; the naive user wouldn't be happy with the result of `help?> LogScore`). I'm not familiar enough with `@create_docs` to write a reasonable pull request in a minute.

p.s. it seems the [documentation](https://juliaai.github.io/MLJBase.jl/stable/) is outdated (also, why does `LogLoss` etc. not appear in "measures" but only in "utility functions"?).

**Comment by ablaom** [comment]
Closing in favour of #717 and #718 and https://github.com/alan-turing-institute/MLJ.jl/issues/890
