### ISSUE TITLE
For a 0.20 release

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBase.jl#725]
The following are PR's onto the [for-a-0-point-20-release](https://github.com/JuliaAI/MLJBase.jl/tree/for-a-0-point-20-release) branch which will ultimately be merged onto `dev`. 

- [x] https://github.com/JuliaAI/MLJBase.jl/pull/724
- [x] https://github.com/JuliaAI/MLJBase.jl/pull/733
- [x] https://github.com/JuliaAI/MLJBase.jl/pull/732

**Comment by olivierlabayle** [comment]
Since we are breaking the serialization API, I am pondering the `kwargs...` argument too. Any rationale/use case for this? 

A difficulty will occur when saving composite machines that may contain models with the same set of kwargs I think.

**Comment by ablaom** [comment]
@olivierlabayle Yes, as discussed in our call, there's good reason to drop this. Can you go ahead and include the change in your planned MLJBase PR?

**Comment by olivierlabayle** [comment]
Yes sure!

Here is the tracking list for the migration:

- [ ] `Save` and `update!` control --> MLJIteration.jl : **target branch dev**
- [ ] `save(model::MLJTuning.EitherTunedModel,...`, `restore(model::MLJTuning.EitherTunedModel,...` --> MLJTuning.jl : **target branch dev**
- [ ] `save(model::MLJEnsembles.EitherEnsembleModel,...`, `restore(model::MLJEnsembles.EitherEnsembleModel,...` --> MLJEnsembles.jl : **target branch dev**
- [ ] Everything else --> MLJBase.jl : **target branch for-a-0-point-20-release**

From what I have seen, no new dependency should be created. I will let you review and synchronize the various merges.

**Comment by ablaom** [comment]
@olivierlabayle Thanks for tracking this.

I'm reluctant to include the first (now crossed out) migration, as in my experience such moves are sometimes breaking for the target, and I think we can live without it, no? I don't think we're ready to break MLJModelInterface at this point. 

Otherwise this looks good.

**Comment by ablaom** [comment]
> Would you mind adding me to: MLJModelInterface, MLJTuning and MLJEnsembles so that I don't have fork the repositories?

Done.

**Comment by olivierlabayle** [comment]
@ablaom All PR are ongoing! I will follow along your reviews and make appropriate changes.
