### ISSUE TITLE
MLJBase fails to precompile

### ISSUE THREAD

**Issue by hoelzl** [JuliaAI/MLJBase.jl#734]
When trying to install MLJBase into an freshly created project I get the following error message:

```
(TestMLJ) pkg> add MLJ
    Updating registry at `C:\Users\tc\.julia\registries\General.toml`
   Resolving package versions...
    Updating `C:\Users\tc\Programming\Julia\Courses\YouTube\TestMLJ\Project.toml`
  [add582a8] + MLJ v0.17.1
    Updating `C:\Users\tc\Programming\Julia\Courses\YouTube\TestMLJ\Manifest.toml`
[...]
  [add582a8] + MLJ v0.17.1
  [a7f614a8] + MLJBase v0.19.5
[...]
Precompiling project...
  ✗ MLJBase
  ✗ MLJIteration
  1 dependency successfully precompiled in 10 seconds (86 already precompiled)
  2 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages
[...]
```
The environment is as follows:
```
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)
```
I'm not sure whether this might be related to #715; I've removed all packages from the global `v1.7` project and the `TestMLJ` folder is not nested inside another project, so it doesn't seem to be related to the problems with nested packages mentioned in the discussion of that issue. Furthermore, installation fails with a similar error if I try to install into the `v1.7` project, so this also seems to be different from [this discussion](https://discourse.julialang.org/t/unable-to-precompile-differentialequations-jl-in-juno-ide-in-new-environment-and-empty-project/71608).

The complete error log is attached here: [mlj-installation-error.txt](https://github.com/JuliaAI/MLJBase.jl/files/7983498/mlj-installation-error.txt).

**Comment by ablaom** [comment]
Mmm. This is tricky. I'm not able to reproduce. Here's what I have:

```julia
(@work) pkg> activate --temp
  Activating new project at `/var/folders/4n/gvbmlhdc8xj973001s6vdyw00000gq/T/jl_h3Qe5E`

(jl_h3Qe5E) pkg> add MLJ
Precompiling project...
  83 dependencies successfully precompiled in 48 seconds (5 already precompiled)

(jl_h3Qe5E) pkg> st
      Status `/private/var/folders/4n/gvbmlhdc8xj973001s6vdyw00000gq/T/jl_h3Qe5E/Project.toml`
  [add582a8] MLJ v0.17.1
```

Here's what I'm stacking on top of:

```julia
(jl_h3Qe5E) pkg> activate
  Activating project at `~/.julia/environments/v1.7`

(@v1.7) pkg> st
      Status `~/.julia/environments/v1.7/Project.toml`
  [295af30f] Revise v3.3.1
  [44cfe95a] Pkg
  [8dfed614] Test

```

And

```julia
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_LTS_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_EGLOT_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_NUM_THREADS = 5
  JULIA_NIGHTLY_PATH = /Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia
```

I also have no issue if I completely empty the `v1.7` environment as  you did. 

I'd say this is some kind of Julia bug and you'd be entitled to post there. I take it you have the same issue if you add in steps, say: `add MLJModelInterface`, `add ScientificTypes`, `add MLJBase`, `add MLJIteration`, `add MLJModels`, `add MLJIteration`, `add MLJSerialization`, `add MLJEnsembles`?



And julia 1.6 works fine?

**Comment by ablaom** [comment]
@OkonSamuel You have a windows machine, yes? Are you able to reproduce?

**Comment by hoelzl** [comment]
You are probably correct that this is a Julia bug: Further testing shows that the error appears for many different packages, even ones I previously installed successfully in other projects. MLJBase just seems to have been the first package to trigger the issue.

Julia 1.6 works fine. Reinstalling Julia 1.7.1 didn't fix the problem, but after removing the `.julia` directory, Julia 1.7.1 can install MLJ without problems. Maybe some file in the depot became corrupted and broke precompilation; in any case it seems unlikely that MLJBase is really the culprit.

Thank you for your help and sorry for taking up your time with an issue that turns out to not be related to MLJBase!

**Comment by ablaom** [comment]
> Thank you for your help and sorry for taking up your time with an issue that turns out to not be related to MLJBase!

No problem! It's good to know this.
