### ISSUE TITLE
unpack error

### ISSUE THREAD

**Issue by eisthf** [JuliaAI/MLJBase.jl#777]
```julia
using MLJ

iris = load_iris();
y, X = unpack(iris, ==(:target); rng=123);
```

Calling `unpack()` may or may not error depending on Julia version (tested only on Windows)

On Julia 1.7.2, 1.7.3, `unpack()` throws the following error message:

> ERROR: BoundsError: attempt to access Tuple{CategoricalArrays.CategoricalVector{String, UInt32, String, CategoricalArrays.CategoricalValue{String, UInt32}, Union{}}} at index [2] 

On Julia 1.8.0-beta1, 1.8.0-beta 3, it works fine.

**Comment by ablaom** [comment]
@eisthf Thanks for reporting 🙏🏾 

Can you please report the output of `using Pkg; Pkg.status()`?

**Comment by eisthf** [comment]
Here are the `Pkg.status()` outputs for 1.7 and 1.8 environment:

```julia
julia> using Pkg; Pkg.status()
      Status `E:\.julia\environments\v1.7\Project.toml`
  [c52e3926] Atom v0.12.36
  [6e4b80f9] BenchmarkTools v1.3.1
  [336ed68f] CSV v0.10.4
  [8be319e6] Chain v0.4.10
  [534720e6] CompositeStructs v0.1.2
  [79afa230] Continuables v1.0.1
  [a93c6f00] DataFrames v0.21.8
  [864edb3b] DataStructures v0.18.11
  [31c24e10] Distributions v0.24.18
  [e30172f5] Documenter v0.26.3
  [35a29f4d] DocumenterTools v0.1.13
  [7876af07] Example v0.5.4 `E:\.julia\dev\Example`
  [38e38edf] GLM v1.7.0
  [e9467ef8] GLMakie v0.5.5
  [c43c736e] Genie v4.18.0
  [c27321d9] Glob v1.3.0
  [cd3eb016] HTTP v0.9.17
  [0e44f5e4] Hwloc v2.0.0
  [ac1192a8] HypertextLiteral v0.9.3
  [7073ff75] IJulia v1.23.3
  [0f8b85d8] JSON3 v1.9.4
  [e5e0dc1b] Juno v0.8.4
  [23fbe1c1] Latexify v0.15.14
  [50d2b5c4] Lazy v0.15.1
  [2fda8390] LsqFit v0.12.1
  [f0e99cf1] MLBase v0.8.0
  [add582a8] MLJ v0.16.5
  [a7f614a8] MLJBase v0.18.2
  [c6f25543] MLJDecisionTreeInterface v0.1.4
  [6ee0df7b] MLJLinearModels v0.6.2
  [1914dd2f] MacroTools v0.5.9
  [c03570c3] Memoize v0.4.4
  [a45c323d] MyAwesomePackage v0.1.1 `https://github.com/eisthf/MyAwesomePackage#master`
  [d92e12fc] NPFinancial v0.3.1
  [5fb14364] OhMyREPL v0.5.12
  [d96e819e] Parameters v0.12.3
  [14b8a8f1] PkgTemplates v0.7.26
  [91a5bcdd] Plots v1.27.6
  [c3e4b0f8] Pluto v0.19.3
  [2fc8631c] PlutoSliderServer v0.3.10
  [7f904dfe] PlutoUI v0.7.1
  [08abe8d2] PrettyTables v1.3.1
  [49802e3a] ProgressBars v1.4.1
  [92933f4c] ProgressMeter v1.7.2
  [438e738f] PyCall v1.93.1
  [ce6b1742] RDatasets v0.7.7
  [295af30f] Revise v3.3.3
  [3646fa90] ScikitLearn v0.6.4
  [699a6c99] SimpleTraits v0.9.4
  [2913bbd2] StatsBase v0.33.16
  [09ab397b] StructArrays v0.6.5
  [28013501] TAOSimul v0.1.0 `E:\.julia\dev\TAOSimul`
  [bd369af6] Tables v1.7.0
  [fdbf4ff8] XLSX v0.7.9
  [10745b16] Statistics
```


```julia
julia> using Pkg; Pkg.status()
Status `E:\.julia\environments\v1.8\Project.toml`
⌃ [c52e3926] Atom v0.12.36
  [336ed68f] CSV v0.10.4
  [db3c262e] Calculator v0.1.0 `..\..\..\Document\books\Julia\Julia Best Practice\9781838648817_Code\Chapter02\Calculator`
⌃ [a93c6f00] DataFrames v1.3.2
⌃ [31c24e10] Distributions v0.25.53
  [7876af07] Example v0.5.4 `E:\.julia\dev\Example`
⌃ [38e38edf] GLM v1.7.0
⌃ [c43c736e] Genie v4.17.0
  [7073ff75] IJulia v1.23.3
  [e5e0dc1b] Juno v0.8.4
  [2fda8390] LsqFit v0.12.1
  [f0e99cf1] MLBase v0.9.0
⌃ [add582a8] MLJ v0.18.1
  [c6f25543] MLJDecisionTreeInterface v0.2.2
  [6ee0df7b] MLJLinearModels v0.6.2
  [5ae90465] MLJScikitLearnInterface v0.2.0
  [5fb14364] OhMyREPL v0.5.12
⌃ [91a5bcdd] Plots v1.27.5
  [92933f4c] ProgressMeter v1.7.2
  [438e738f] PyCall v1.93.1
  [ce6b1742] RDatasets v0.7.7
  [b95f3570] Rater v0.1.0 `..\..\..\Document\books\Julia\Julia Best Practice\9781838648817_Code\Chapter02\Rater`
  [295af30f] Revise v3.3.3
  [3646fa90] ScikitLearn v0.6.4
  [2913bbd2] StatsBase v0.33.16
  [bd369af6] Tables v1.7.0
⌃ [fdbf4ff8] XLSX v0.7.9
  [10745b16] Statistics
Info Packages marked with ⌃ have new versions available

```

**Comment by OkonSamuel** [comment]
> ```julia
> using MLJ
> 
> iris = load_iris();
> y, X = unpack(iris, ==(:target); rng=123);
> ```

@eisthf The code snippet runs without error on my Windows PC. I tested it with Julia 1.71 and Julia 1.7.3. 

The error you are experiencing  is because you were trying to access the second index of a one-element tuple. The code `unpack(iris, ==(:target); rng=123);` actually returns a one-element tuple 

`(CategoricalArrays.CategoricalValue{String, UInt32}["setosa", "setosa", "setosa", "setosa", "setosa", "setosa", "setosa", "setosa", "setosa", "setosa"  …  "virginica", "virginica", "virginica", "virginica", "virginica", "virginica", "virginica", "virginica", "virginica", "virginica"],)`.

To get your desired outcome you should have used `y, X = unpack(iris, ==(:target), col -> true; rng=123);` .

I know your thinking that this is a little confusing,  yes I agree with you. That is why we changed the syntax slightly in MLJBase >= v0.19.0 and MLJ >= v0.17.0 to conform to exacting what you did above.  So another way to resolve your issue is just to update your version of MLJ to >= 0.17.0. (Currently you are using MLJ v0.16.5).

Feel free to close this issue if your satisfied.

**Comment by eisthf** [comment]
Oh I got it. I've just upgraded MLJ and it's working well now. Thank you!

**Comment by ablaom** [comment]
@OkonSamuel @eisthf 

As of MLJBase 0.19 it is no longer necessary to specify the second predicate `col -> true`. See [these release notes](https://github.com/JuliaAI/MLJBase.jl/releases/tag/v0.19.0). The posted code snippet indeed works as expected in recent versions but @eisthf was running using an old version.

@eisthf It looks like you bundle all you packages into the default 1.7 environment, which can make it challenging to keep all packages up to date. If one of the packages you use falls behind in maintaining compatibility with upgraded dependencies, it will pull all the others down with it.

**Comment by eisthf** [comment]
@ablaom Thank you for the kind suggestion. I will be more cautious about versions from now on. And yes I will keep that in mind that using a separate enviroment for a particular application is desirable!
