### ISSUE TITLE
type parameter issue

### ISSUE THREAD

**Issue by nsajko** [JuliaAI/MLJBase.jl#834]
Take a look at the function declaration here: https://github.com/JuliaAI/MLJBase.jl/blob/dev/src/measures/finite.jl#L536-L538

Firstly, the `T` and `U` type parameters are unbound (this causes performance issues).

I suspect that `average=macro_avg` in the function declaration was intended to look like this: `average::T = macro_avg` instead.

Similarly with `return_type=LittleDict`: `return_type::Type{U} = LittleDict`.

**Comment by ablaom** [comment]
I agree this doesn't quite look right and the  suggested remedy is appropriate. Be great if you make a PR for this. 

And, as I have already noticed, the preceding lines (under my name "@ablaom") also seem redundant.

**Comment by ablaom** [comment]
Closed by #848
