### ISSUE TITLE
Issue in `serializable`

### ISSUE THREAD

**Issue by ericphanson** [JuliaAI/MLJBase.jl#843]
https://github.com/JuliaAI/MLJBase.jl/blob/0d8400a7e5f510cd0fb6243a79b5a8e2bd1c0461/src/machines.jl#L909

should be
```julia
 copymach = Machine(mach.model, mach.args..., cache=C) 
```
because `args` may be empty (if the model has already been serialized once), and we shouldn't need to do the checks again.

Ref https://github.com/alan-turing-institute/MLJ.jl/issues/965 which has a reproducible example of this (the `serializable` call), along with other issues.

**Comment by ablaom** [comment]
An upcoming PR refactors these methods and, I believe, renders this issue mute: https://github.com/JuliaAI/MLJBase.jl/blob/1739d80019778dcc5fb3420883b3b6f3c9b251c9/src/machines.jl#L967

(new `replace(machine, ....)` method does not apply checks)

**Comment by ablaom** [comment]
Closing as addressed in #841
