### ISSUE TITLE
Avoid printing empty NamedTuples like empty tuples

### ISSUE THREAD

**Issue by andreasnoack** [JuliaAI/MLJBase.jl#846]
It can be pretty confusing
```julia
julia> (;)
()

julia> ()
()

julia> (;) == ()
false
```
so it would nice to print the empty case as `NamedTuple()`.

**Comment by ablaom** [comment]
Makes sense. I expect the change would happen here: 

https://github.com/JuliaAI/MLJBase.jl/blob/d2af6bd2ca7b85399db0cf79a1f96f738d342aea/src/show.jl#L72

**Comment by ablaom** [comment]
In #841 items returned by `report(mach)` and `fitted_params(mach)` with empty named tuple values (or `nothing`) are dropped.
