### ISSUE TITLE
allow `train_test_pairs` to work on generic vector `y`?

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaAI/MLJBase.jl#847]
after a long time, I still cannot figure out how to get
```julia
	class_labels = vcat(["spam" for _ = 1:3], ["not spam" for i = 1:9])
	ttp = train_test_pairs(kf, 1:length(class_labels), class_labels)
	for (k, (ids_train, ids_test)) in enumerate(ttp)
		# train on ids_train
		# test on ids_test
	end
```
to work. would be nice to allow `train_test_pairs` to accept a generic vector of class labels so that this can be used outside the context of ML workflows in this package. I'm looking for something generic like scikitlearn's stratified K-folds. thanks!

the error I get is:

```
ArgumentError: Supplied target has scitype AbstractVector{ScientificTypesBase.Textual} but stratified cross-validation applies only to classification problems.

    train_test_pairs(::MLJBase.StratifiedCV, ::UnitRange{Int64}, ::Vector{String})@resampling.jl:407
    top-level scope@[Local: 3](http://localhost:1235/edit?id=c4c85f16-4c12-11ed-3b74-134639249bb1#)[inlined]
```

**Comment by SimonEnsemble** [comment]
I needed:
```julia
train_test_pairs(kf, 1:length(y_train), y_train |> categorical)
```
which I discovered from https://github.com/JuliaAI/MLJBase.jl/pull/276. not intuitive or necessary to me, as a user, just importing a few functions from `MLJBase`...

**Comment by ablaom** [comment]
@SimonEnsemble Thanks for reporting. 

In MLJ more generally, care is taken to track all levels of categorical data, not just those seen in a give sample.  However, in this particular case, the full class pool is not used (or needed) so I agree there's a good argument to make this more generic. I think the test triggering the warning can just be removed.
