### ISSUE TITLE
Confused about output of `predict(MLJBase.Pipeline, fitresult, Xnew)`

### ISSUE THREAD

**Issue by pat-alt** [JuliaAI/MLJBase.jl#870]
In [`ConformalPrediction.jl`](https://github.com/pat-alt/ConformalPrediction.jl) we fit and predict from atomic MLJ models iteratively to conformalise them. For this we rely on calling `MMI.predict(atomic_model,fitresult,Xnew)` to produce fitted values (see for example [here](https://github.com/pat-alt/ConformalPrediction.jl/blob/5a868482641d43ed938273a0853f97ba903f008d/src/ConformalModels/transductive_regression.jl#L41)). Since pipelines are just models, we should also be able to use pipelines as atomic models as I've done [here](https://www.paltmeyer.com/ConformalPrediction.jl/dev/regression/#Model).

However, I noted that `predict(MLJBase.Pipeline, fitresult, Xnew)` produces a tuple, as opposed to a vector of outputs. Consider the following example:

```julia
using MLJ
X, y = MLJ.make_regression()
LinearRegressor = @load LinearRegressor pkg=MLJLinearModels
degree_polynomial = 10
polynomial_features(X, degree::Int) = reduce(hcat, map(i -> X.^i, 1:degree))
model = LinearRegressor()
pipe = (X -> MLJ.table(polynomial_features(MLJ.matrix(X), degree_polynomial))) |> model

mach_model = machine(model, X, y)
fit!(mach_model)
mach_pipe = machine(pipe, X, y)
fit!(mach_pipe)
```

Calling predict on the model yields:

```julia
julia> predict(mach_model.model, mach_model.fitresult, selectrows(X,1))
╭───────────────────────────────────╮
│                                   │
│      (1)   1.6213537498581336     │
│                                   │
│                                   │
╰─────────────────────── 1 items ───╯
```

Calling predict on the pipeline yields:

```julia
julia> predict(mach_pipe.model, mach_pipe.fitresult, selectrows(X,1))
([1.6690430206823992], NamedTuple())
```

Is there a reason for this? If so, is there a way to specify that I only want the actual predictions? Note that when wrapping the pipeline in a machine, this behaviour does not occur. Should I just use machines to get predictions from atomic models?

Thanks!

**Comment by ablaom** [comment]
Starting in MLJBase 0.21, `predict` and `transform` in  pipelines and stacks (and more generally in `*CompositeNetwork`models) output an extra `report` item, when dispatched on a *model*. Calling them on a machine is no different from before. This is described in the [release notes](https://github.com/JuliaAI/MLJBase.jl/releases/tag/v0.21.0) but has tripped up a few users; see [here](https://github.com/JuliaAI/MLJBase.jl/issues/867) for more.

**Comment by pat-alt** [comment]
Got it, thanks @ablaom 😃
