### ISSUE TITLE
Diagonal lines in `roc_curve` points

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaAI/MLJBase.jl#882]
When using `roc_curve`, I sometimes get areas in the Receiver Operating Characteristic (ROC) curve that are missing points. For example, the following shows straight lines at the left bottom:

![image](https://user-images.githubusercontent.com/20724914/219612008-c0bcd7ff-20a9-45c5-b47a-a93fc358e4b4.png)

And for an earlier paper, I got this:

![image](https://user-images.githubusercontent.com/20724914/219612281-3781757e-b981-420c-ba7a-c9a228d2a6f8.png)

@ablaom Do you happen to know whether my understanding is correct that this is caused by a lack of data points in those areas? So, when raising the threshold of the model, it will just jump past X observations in one step. Is there something that I can learn from this? Maybe that my model is not complex enough?

**Comment by ablaom** [comment]
Sorry, probably this is dumb question, but are your plots for *out-of-sample* predictions or training predictions?

**Comment by ablaom** [comment]
Thanks for raising this question, investigating, and for the assurances about `roc`.
