### ISSUE TITLE
Update to LossFunctions.jl v0.9

### ISSUE THREAD

**Issue by juliohm** [JuliaAI/MLJBase.jl#896]
@ablaom we refactored LossFunctions.jl and changed the order of output and prediction arguments to be more consistent with other ecosystems as you requested at some point in the past. Can you please update this package to use the latest release?

We also removed the ObsDim submodule and the OrdinalMarginLoss as they were not very useful nor very used in downstream projects we maintain.

**Comment by juliohm** [comment]
cc: @OkonSamuel

**Comment by ablaom** [comment]
@juliohm Thanks for flagging.
