### ISSUE TITLE
Update to LossFunctions.jl v0.10

### ISSUE THREAD

**Issue by juliohm** [JuliaAI/MLJBase.jl#902]
We are gradually cleaning up the LossFunctions.jl package, simplifying the interface and making the code more general. Can you please review the latest changes and bump the version here again?

The main breaking changes from v0.9 to v0.10 are:

1. The `value(loss, yhat, y)` function is replaced by the functor `loss(yhat, y)`
2. The AggMode submode is gone in favor of `sum(loss, yhats, ys, [weights])` and `mean(loss, yhats, ys, [weights])`

cc: @ablaom @OkonSamuel

**Comment by ablaom** [comment]
@juliohm It seems that calling behaviour of loss functions has also  changed:

In 0.9:
```julia
julia> loss = DWDMarginLoss(1.0)
DWDMarginLoss{Float64}(1.0)

julia> yhat = [-0.5, 0.5, 0.2]
3-element Vector{Float64}:
 -0.5
  0.5
  0.2

julia> y = [-1, 1 , 1]
3-element Vector{Int64}:
 -1
  1
  1

julia> loss(yhat, y)
3-element Vector{Float64}:
 0.5
 0.5
 0.8
```

In 0.10:
```julia
julia> loss(yhat, y)
ERROR: MethodError: no method matching (::DWDMarginLoss{Float64})(::Vector{Float64}, ::Vector{Int64})
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

Now that `value` is gone, what is the preferred way to apply losses to vectors? Am I expected to just broadcast?

**Comment by juliohm** [comment]
> Am I expected to just broadcast?

Exactly. We let Julia do the work as it is more idiomatic and can fuse with other outer calls.
