### ISSUE TITLE
metrics when the target contains missing

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/MLJBase.jl#93]
I believe that at the moment metrics like `missclassification_rate` will fail if the  target `y` has missings.
The lazy way around it is to just skip entries for which it's missing, are we happy with this? if so I can  implement that for all of 'our' metrics (not sure what LossFunctions does)

**Comment by ablaom** [comment]
Since there are very few supervised models that support missing values in the target, I think any addition to the status quo is pretty low priority. But thanks anyway. I'm closing for now.

**Comment by tlienart** [comment]
yes that's true, but measures could be used outside of training and a case where this happens for us is as follows:

1. Train 
2. predict on XTest, get ypred
3. compare ypred with ytest, ytest has missings.

**Comment by ablaom** [comment]
Fair enough, good point.

**Comment by ablaom** [comment]
This is now resolved.
