### ISSUE TITLE
Post issues pointing to MLJBase 1.0 migration guide

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBase.jl#937]
The following issue can be used as a template:

https://github.com/JuliaAI/Imbalance.jl/issues/58

### Under the JuliaAI umbrella:

- [ ] CatBoost
- [ ] MLJClusteringInterface
- [ ] MLJDecisionTreeInterface
- [ ] MLJGLMInterface
- [ ] MLJLIBSVMInterface
- [ ] MLJLinearModels
- [x] MLJModels
- [ ] MLJMultivariateStatsInterface
- [ ] MLJNaiveBayesInterface
- [ ] MLJScikitLearnInterface
- [ ] MLJTSVDInterface
- [ ] MLJTestInterface
- [ ] MLJText
- [ ] MLJXGBoostInterface
- [ ] NearestNeighborModels

### Other orgs:

- [ ] BetaML
- [ ] EvoLinear
- [ ] EvoTrees
- [ ] LightGBM
- [ ] MLJFlux
- [ ] OneRule
- [ ] OutlierDetectionNeighbors
- [ ] OutlierDetectionPython
- [ ] ParallelKMeans
- [ ] PartialLeastSquaresRegressor
- [x] SIRUS
- [ ] SelfOrganizingMaps
- [ ] SymbolicRegression

@DilumAluthge I recall there is some Julia tool for automating this kind of thing across multiple repos in an org. Can you point me the right direction?

**Comment by DilumAluthge** [comment]
For making PRs (e.g. to set up or modify CI workflow files), we have MassInstallAction.jl.

I don't think we have a Julia package specifically for this kind of issues task. However, we do have GitHub.jl which is a general-purpose GitHub API package. You could likely use GitHub.jl to write a script to open issues on all of the relevant repos.

**Comment by ablaom** [comment]
This didn't really happen, and it isn't really mattering too much. Closing.
